/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmpf;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class EditForm extends javax.swing.JFrame {
    boolean checkEmptyItem = false, checkWrongExtension = false, checkMaxItem = false;
    String fileName, extension;
    /**
     * Creates new form EditForm
     */
    public EditForm() {
        initComponents();
        try {
            for(int i=0; i < UserList.imagePath.size(); i++)
            {
                Image img = ImageIO.read(new File(UserList.imagePath.elementAt(i)));
                ImageIcon icon = new ImageIcon(img.getScaledInstance(125, 125, Image.SCALE_DEFAULT));
                
                switch (i) {
                    case 0:
                        lblImage1.setIcon(icon);
                        break;
                    case 1:
                        lblImage2.setIcon(icon);
                        break;
                    case 2:
                        lblImage3.setIcon(icon);
                        break;
                    case 3:
                        lblImage4.setIcon(icon);
                        break;
                    default:
                        break;
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bottom = new javax.swing.JPanel();
        Component = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BrowsePanel = new javax.swing.JPanel();
        txtImagePath = new javax.swing.JTextField();
        btnImagePath = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtItemPrice = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        Middle = new javax.swing.JPanel();
        ButtonRow = new javax.swing.JPanel();
        btnRemove1 = new javax.swing.JButton();
        btnRemove2 = new javax.swing.JButton();
        btnRemove3 = new javax.swing.JButton();
        btnRemove4 = new javax.swing.JButton();
        ImageRow = new javax.swing.JPanel();
        lblImage1 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        lblImage3 = new javax.swing.JLabel();
        lblImage4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Main.setBackground(new java.awt.Color(236, 244, 190));
        Main.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bluejack Market");
        jLabel1.setOpaque(true);
        Main.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        Bottom.setOpaque(false);
        Bottom.setLayout(new java.awt.BorderLayout());

        Component.setOpaque(false);
        Component.setLayout(new java.awt.GridLayout(4, 2));

        jLabel2.setText("Item Image :");
        Component.add(jLabel2);

        BrowsePanel.setOpaque(false);
        BrowsePanel.setLayout(new java.awt.GridLayout(1, 2));

        txtImagePath.setEnabled(false);
        BrowsePanel.add(txtImagePath);

        btnImagePath.setText("Browse..");
        btnImagePath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagePathMouseClicked(evt);
            }
        });
        BrowsePanel.add(btnImagePath);

        Component.add(BrowsePanel);

        jLabel3.setText("Item Name:");
        Component.add(jLabel3);
        Component.add(txtItemName);

        jLabel4.setText("Item Price :");
        Component.add(jLabel4);
        Component.add(txtItemPrice);

        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        Component.add(btnReset);

        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        Component.add(btnAdd);

        Bottom.add(Component, java.awt.BorderLayout.CENTER);

        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        Bottom.add(btnBack, java.awt.BorderLayout.SOUTH);

        Main.add(Bottom, java.awt.BorderLayout.PAGE_END);

        Middle.setOpaque(false);
        Middle.setLayout(new java.awt.BorderLayout());

        ButtonRow.setOpaque(false);
        ButtonRow.setLayout(new java.awt.GridLayout(1, 4));

        btnRemove1.setText("Remove");
        btnRemove1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemove1MouseClicked(evt);
            }
        });
        ButtonRow.add(btnRemove1);

        btnRemove2.setText("Remove");
        btnRemove2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemove2MouseClicked(evt);
            }
        });
        ButtonRow.add(btnRemove2);

        btnRemove3.setText("Remove");
        btnRemove3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemove3MouseClicked(evt);
            }
        });
        ButtonRow.add(btnRemove3);

        btnRemove4.setText("Remove");
        btnRemove4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemove4MouseClicked(evt);
            }
        });
        ButtonRow.add(btnRemove4);

        Middle.add(ButtonRow, java.awt.BorderLayout.PAGE_END);

        ImageRow.setOpaque(false);
        ImageRow.setLayout(new java.awt.GridLayout(1, 4));
        ImageRow.add(lblImage1);
        ImageRow.add(lblImage2);
        ImageRow.add(lblImage3);
        ImageRow.add(lblImage4);

        Middle.add(ImageRow, java.awt.BorderLayout.CENTER);

        Main.add(Middle, java.awt.BorderLayout.CENTER);

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        for(int i=0; i < UserList.imagePath.size(); i++)
        {
            if(UserList.imagePath.elementAt(i).equals(""))
            {
                checkEmptyItem = true;
                break;
            }
        }
        
        if(!checkEmptyItem)
        {
            new MainForm().setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Item must be 4 to be sold!");
        }
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnRemove1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemove1MouseClicked
        // TODO add your handling code here:
        UserList.imagePath.setElementAt("",0);
        btnRemove1.setVisible(false);
        lblImage1.setIcon(null);
        revalidate();
    }//GEN-LAST:event_btnRemove1MouseClicked

    private void btnRemove2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemove2MouseClicked
        // TODO add your handling code here:
        UserList.imagePath.setElementAt("",1);
        btnRemove2.setVisible(false);
        lblImage2.setIcon(null);
        revalidate();
    }//GEN-LAST:event_btnRemove2MouseClicked

    private void btnRemove3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemove3MouseClicked
        // TODO add your handling code here:
        UserList.imagePath.setElementAt("",2);
        btnRemove3.setVisible(false);
        lblImage3.setIcon(null);
        revalidate();
    }//GEN-LAST:event_btnRemove3MouseClicked

    private void btnRemove4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemove4MouseClicked
        // TODO add your handling code here:
        UserList.imagePath.setElementAt("",3);
        btnRemove4.setVisible(false);
        lblImage4.setIcon(null);
        revalidate();
    }//GEN-LAST:event_btnRemove4MouseClicked

    private void btnImagePathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagePathMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File choosenFile =  fileChooser.getSelectedFile();
            txtImagePath.setText(choosenFile.getPath());
            
            extension = choosenFile.getPath().substring(choosenFile.getPath().lastIndexOf(".")+1,choosenFile.getPath().length());
            
            if(!extension.equals("jpg") && !extension.equals("png"))
            {
                checkWrongExtension = true;
            }
            else
            {
                checkWrongExtension = false;
                fileName = choosenFile.getName();    
            }
        }
        
    }//GEN-LAST:event_btnImagePathMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
         for(int i=0; i< UserList.imagePath.size(); i++)
        {
            if(!UserList.imagePath.elementAt(i).equals(""))
            {
                
                checkMaxItem = true;
            }
            else
            {
                checkMaxItem = false;
                break;
            }
        }
        if(txtItemName.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Item Name must be filled!");
        }
        else if(txtItemPrice.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Item Price must be filled!");
        }
        else if(!checkIsNumber(txtItemPrice.getText()))
        {
            JOptionPane.showMessageDialog(null, "Item Price must be a number!");
        }
        else if(checkWrongExtension || txtImagePath.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Item Image must be ‘jpg’ or ‘png’!");
        }
        else if(checkMaxItem)
        {
            JOptionPane.showMessageDialog(null, "Items List is full!");
        }
        else
        {
            for(int i=0; i< UserList.imagePath.size(); i++)
            {
                if(UserList.imagePath.elementAt(i).equals(""))
                {
                    UserList.itemName.setElementAt(txtItemName.getText(), i);
                    UserList.itemPrice.setElementAt(Integer.parseInt(txtItemPrice.getText()), i);
                        
                    File originalFile = new File(txtImagePath.getText());
                    File newFilePath = new File(System.getProperty("user.dir") + "\\Assets\\" + fileName);
                    
                    try {
                        Files.copy(originalFile.toPath(), newFilePath.toPath(), StandardCopyOption.REPLACE_EXISTING);
                    } catch (IOException ex) {
                        Logger.getLogger(EditForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    UserList.imagePath.setElementAt("Assets\\\\" + fileName, i);
                    reset();
                    break;
                }
            }
        } 
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetMouseClicked
    
    public void reset()
    {
        checkEmptyItem = false;
        checkWrongExtension = false; 
        checkMaxItem = false;
        fileName = null;
        extension = null;
        txtImagePath.setText("");
        txtItemName.setText("");
        txtItemPrice.setText("");
        
        try {
            for(int i=0; i < UserList.imagePath.size(); i++)
            {
                if(UserList.imagePath.elementAt(i).equals(""))
                {
                    continue;
                }
                else
                {
                    Image img = ImageIO.read(new File(UserList.imagePath.elementAt(i)));
                    ImageIcon icon = new ImageIcon(img.getScaledInstance(125, 125, Image.SCALE_DEFAULT));

                    switch (i) 
                    {
                        case 0:
                            lblImage1.setIcon(icon);
                            btnRemove1.setVisible(true);
                            revalidate();
                            break;
                        case 1:
                            lblImage2.setIcon(icon);
                            btnRemove2.setVisible(true);
                             revalidate();
                            break;
                        case 2:
                            lblImage3.setIcon(icon);
                            btnRemove3.setVisible(true);
                             revalidate();
                            break;
                        case 3:
                            lblImage4.setIcon(icon);
                            btnRemove4.setVisible(true);
                             revalidate();
                            break;
                        default:
                            break;
                    }
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public boolean checkIsNumber(String text)
    {
        try 
        {
            Integer.parseInt(text);
            return true;
        }
        catch (NumberFormatException e) {
             return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel BrowsePanel;
    private javax.swing.JPanel ButtonRow;
    private javax.swing.JPanel Component;
    private javax.swing.JPanel ImageRow;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Middle;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnImagePath;
    private javax.swing.JButton btnRemove1;
    private javax.swing.JButton btnRemove2;
    private javax.swing.JButton btnRemove3;
    private javax.swing.JButton btnRemove4;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImage3;
    private javax.swing.JLabel lblImage4;
    private javax.swing.JTextField txtImagePath;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    // End of variables declaration//GEN-END:variables
}
